---
- name: 'Configure WIFI'
  copy: src=./wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Update cache'
  apt: update_cache=yes

- name: 'Ignore Woflram - which is failing to install and is also annoyingly huge. Why the eff is this installed by default!'
  shell: apt-mark hold wolfram-engine

- name: 'Upgrade full'
  command: apt-get upgrade

- name: Check if node path exists
  stat: path=/usr/bin/node
  register: check_node

- name: Check if npm path exists
  stat: path=/usr/bin/npm
  register: check_npm

- name: 'Get node'
  command: wget http://nodejs.org/dist/v0.10.2/node-v0.10.2-linux-arm-pi.tar.gz
  when: check_node.stat.exists == false

- name: 'Untar node'
  command: tar -xvzf node-v0.10.2-linux-arm-pi.tar.gz
  when: check_node.stat.exists == false

- name: 'Symlink node'
  command: ln -s /home/pi/node-v0.10.2-linux-arm-pi/bin/node /usr/bin/node
  when: check_node.stat.exists == false

- name: 'Symlink npm'
  command: ln -s /home/pi/node-v0.10.2-linux-arm-pi/bin/npm /usr/bin/npm
  ignore_errors: True
  when: check_npm.stat.exists == false

- name: 'Reboot'
  command: /sbin/reboot -t now

